### ISSUE TITLE
Kursutveckling vt18 lp3

### ISSUE THREAD

**Issue by mosbth** [dbwebb-se/databas#1]
* Undvik kopiera filerna i SQL-guiden när man hoppar mellan guidens steg.
* Tillåt/Tillåt inte, att stud gör egna vyer i skolan?
* Hur skall lonerevision <arg> implementeras?
* Undvik att använda genererad SQL-kod förn Workbench, be stud skapa egna tabeller för hand.
* Ändra inte i package.json... (dbwebb update)

**Comment by mosbth** [comment]
* "Skulle gärna se mer information om säkerhet"

**Comment by litemerafrukt** [comment]
Från en redovisning kmom04:
> Hade dock önskat mer material om varför och var Express används. Är det ett seriöst projekt eller ett hopkok för hobbybruk? Varför är det så bra med ejs? Jag tycker det är oerhört rörigt och svåröverskådligt. Varför fortsätter vi inte med Apache? Konkreta exempel ger lite trovärdighet till det vi arbetar med.

> Ämnet verkar alldeles för stort för ett en-veckas kursmoment

**Comment by mosbth** [comment]
Rimligt om kmom04. 

Lite udda att många på campus säger att kmom04 var mycket enklare än kmom03.

**Comment by mosbth** [comment]
Går det ge kursen där alternativ implementation är PHP? Jag funderade på det innan kursen, att ha två olika applikationsspråk. Jag får suga på det när kursen har "satt sig".

**Comment by mosbth** [comment]
"Hade varit toppen om det fanns fler "extra uppgifter" med join (LEFT, RIGHT, OUTER, INNER JOIN, joina flera tabeller 3+) så att man kan testa sina kunskaper."

**Comment by mosbth** [comment]
Städa upp i kmom01 för att förtydliga vilka sätt som rekommenderas vid installation av MySQL och klienter.

**Comment by mosbth** [comment]
Dubbelkolla koden som skrivs i kmom02 och kmom03 avseende JS, går den att spetsa till så att man får ett flöde mellan kmom02 och framåt som blir "individuellt".

**Comment by mosbth** [comment]
Bygg om express-koden för att använda andra ikoner (felkälla laddningstid) och eventuellt bootstrap (eller liknande) som css-alternativ för något av de sista exemplen.

Fixa login-exemplet.

**Comment by mosbth** [comment]
Eventuellt visa modul som skriver ut som tabell för cli-program.

**Comment by mosbth** [comment]
## Kmom06

* Rapport för arbetstid återkommer inte i uppgiften
* Att skapa index återkommer inte i uppgiften
* Rapporten med Joins blir "alltför" svår, mycket på en gång. Även svår att rätta.
* Se över flödet mellan guiden och uppgiften.

**Comment by mosbth** [comment]
## Guiden

* Förstärk delen med nycklar, se till att olika nyckelvarianter hanteras såsom sammansatt och auto_increment, eventuellt begreppet kandidatnycklar.

**Comment by mosbth** [comment]
## Index

* (score = 0) för FULLTEXT INDEX

**Comment by lewenhagen** [comment]
Kmom01
-----------------
Information om "safe update mode" kommer efter det dyker upp första gången.
Första gången: https://dbwebb.se/guide/kom-igang-med-sql-i-mysql/lagg-till-rader
Tas upp: https://dbwebb.se/guide/kom-igang-med-sql-i-mysql/ta-bort-rader

**Comment by mosbth** [comment]
### Kursutvärdering kurspaket

Kursutärderingen (kurspaketet) finns på länken: http://bfm.bth.se/public/rapport/eca3fd3d-699d-45cc-9be2-a3e82be4d1a5
13 av 37 svarade, snittet blev 3.38.

I fritextsvaren ser jag ett par kommentarer med önskemål om mer undervisning/video för distans.

Några önskar färre uppgifter och koncentrera mot ett par uppgifter.

Det finns också kommenterar kring JavaScript/Node och förslag om att det var PHP istället. Det är rimligt när det gäller kurspaketet. Kursen samläses med ett annat program och deras krav var Node/JavaScript. Kanske går det göra både ock. Jag är medveten om denna svårigheten.

Kommentar om att förtydliga i guiden  "Flera SQL frågor inuti en" och hur/varför en multiquery fungerar.

**Comment by mosbth** [comment]
## Examinationen ind

* Första uppgiften avsluta med join. Skall synas i både webb och cli. 
* Alla delar i uppg 1 skall synas i cli + webb.
* Förtydliga i sök vad som skall sökas på, inklusive delsträngar och alla kolumner.
* Förtydliga att CRUD skall fungera både med CUD på en av tabellerna.

**Comment by mosbth** [comment]
## Läsanvisningar

* Leta reda på artiklar om större databasmodeller use cases, med erfarenheter och exempel.

**Comment by mosbth** [comment]
## Lösa noteringar från studentfeedback kurspaket.

* Skapa snygga rapporter av den information vi plockar ut
* konceptet med Node.js och express – hur ska jag använda det på min privata hemsida? Eller är det endast för webb-sidor som har en egen server?
* Det jag saknade var lite mer om felhanteringen i express, till exempel flash meddelande. 
* Jag tycker även att normalisering är något som borde tas upp då detta är en väldigt viktig del av att bygga väl fungerande databaser
* tuff kurs för dem som inte har lite JavaScript i grunden
* hade varit intressant att lära sig mer om optimering och jobba med riktigt stora tabeller för att se hur olika sätta att skriva SQL-kod kan påverka prestandan väldigt mycket.
* Alt se över kursplanens beskrivning av kursen (rörande fokus JS).
* Jag hade gärna sätt att det fanns videor eller liknande att tillgå som instruktioner. (rörande JS)
* Något jag verkligen saknade i kursen var mer om säkerhet
* väldigt mycket fokus på JS och Node
* fler tips om vad man ska tänka på när man skapar sin logiska datamodell med relationsmodellen.
* mer exempel på att förhindra användaren att få in felaktiga värden i db och testning/felsökning i allmänhet.
* Kanske lite mer om implementation av sessioner.
* skulle uppskatta mer av är simpla lekmannaförklaringar kring det vi gör, så att man lättare hittar en förståelse för hur saker hänger ihop.
* jag livnär mig på genomgångarna. Laddar ner dem, ser dem och pausar så jag kan koda samtidigt. 
*  The course was a bit confusing in the beginning, or up to kmom06.
* gillar verkligen att det blev genomgångar, det hjälpte än del!
* mer fokus på Joins

**Comment by mosbth** [comment]
Det gick ut ytterligare en utvärdering (den gick inte att stänga av) som finns tillgänglig här:
http://bfm.bth.se/public/rapport/3fea351c-8d80-4bc6-9f3b-e731c3af7da0  

Här ser man en överiskt:
https://imgur.com/a/AsTbMda

Utvärderingen ger ett liknande resultat av det vi sett sedan tidigare (se ovan).
