### ISSUE TITLE
dbwebb init skapar inte min me/ katalog på Mac

### ISSUE THREAD

**Issue by mosbth** [dbwebb-se/databas#13]
Så här skapas me-katalgoen i databas-kursen.

```
desktop:~
$ dbwebb --version
dbwebb version v2.6.8 (2020-10-29)
```

Klona kursrepot.

```
desktop:~
$ dbwebb clone databas
Cloning course-repo for 'databas' from 'https://github.com/dbwebb-se/databas' as 'databas'.
Cloning into 'databas'...
DONE to clone course repo.
desktop:~
$ cd databas/
desktop:~/databas
```

Initiera endast me-katalogen för att debugga.

```
$ dbwebb init-me
Creating and initiating the directory structure in 'me/' (will not overwrite existing files).
me/skolan
me/kmom01/klient
me/kmom02/js
me/kmom02/search
me/kmom02/terminal1
me/kmom03/cli
me/kmom03/terminal2
me/kmom03/er1
me/kmom04/er2
me/kmom04/trans
me/kmom04/myexpress
me/kmom04/express-sql
me/kmom05/prog
me/kmom05/crud
me/kmom05/eshop1
me/kmom06/func
me/kmom06/index
me/kmom06/eshop2
me/kmom10/eshop3
me/kmom10/try1
me/kmom10/try2
me/kmom10/try3
me/kmom10/prep
me/redovisa
DONE to init the directory 'me/'.
```

Så här ser katalogstrukturen ut när det är klart.

```
desktop:~/databas
$ tree me
me
├── kmom01
│   └── klient
├── kmom02
│   ├── js
│   ├── search
│   └── terminal1
├── kmom03
│   ├── cli
│   ├── er1
│   └── terminal2
├── kmom04
│   ├── er2
│   ├── express-sql
│   ├── myexpress
│   └── trans
├── kmom05
│   ├── crud
│   ├── eshop1
│   └── prog
├── kmom06
│   ├── eshop2
│   ├── func
│   └── index
├── kmom10
│   ├── eshop3
│   ├── prep
│   ├── try1
│   ├── try2
│   └── try3
├── redovisa
└── skolan

31 directories, 0 files
```

**Comment by neskoc** [comment]
Allt är likadant fram till  sista steget:
databas]$ tree .
.
├── \033[01;31m\033[Km\033[m\033[K\033[01;31m\033[Ke\033[m\033[K\033[01;31m\033[K
│   ├── \033[m\033[K\033[01;31m\033[Kk\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[Ko\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[K0\033[m\033[K\033[01;31m\033[K1\033[m\033[K\033[01;31m\033[K
│   │   └── \033[m\033[K\033[01;31m\033[Kk\033[m\033[K\033[01;31m\033[Kl\033[m\033[K\033[01;31m\033[Ki\033[m\033[K\033[01;31m\033[Ke\033[m\033[K\033[01;31m\033[Kn\033[m\033[K\033[01;31m\033[Kt\033[m\033[K
│   ├── \033[m\033[K\033[01;31m\033[Kk\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[Ko\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[K0\033[m\033[K\033[01;31m\033[K2\033[m\033[K\033[01;31m\033[K
│   │   ├── \033[m\033[K\033[01;31m\033[Kj\033[m\033[K\033[01;31m\033[Ks\033[m\033[K
│   │   ├── \033[m\033[K\033[01;31m\033[Ks\033[m\033[K\033[01;31m\033[Ke\033[m\033[K\033[01;31m\033[Ka\033[m\033[K\033[01;31m\033[Kr\033[m\033[K\033[01;31m\033[Kc\033[m\033[K\033[01;31m\033[Kh\033[m\033[K
│   │   └── \033[m\033[K\033[01;31m\033[Kt\033[m\033[K\033[01;31m\033[Ke\033[m\033[K\033[01;31m\033[Kr\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[Ki\033[m\033[K\033[01;31m\033[Kn\033[m\033[K\033[01;31m\033[Ka\033[m\033[K\033[01;31m\033[Kl\033[m\033[K\033[01;31m\033[K1\033[m\033[K
│   ├── \033[m\033[K\033[01;31m\033[Kk\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[Ko\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[K0\033[m\033[K\033[01;31m\033[K3\033[m\033[K\033[01;31m\033[K
│   │   ├── \033[m\033[K\033[01;31m\033[Kc\033[m\033[K\033[01;31m\033[Kl\033[m\033[K\033[01;31m\033[Ki\033[m\033[K
│   │   ├── \033[m\033[K\033[01;31m\033[Ke\033[m\033[K\033[01;31m\033[Kr\033[m\033[K\033[01;31m\033[K1\033[m\033[K
│   │   └── \033[m\033[K\033[01;31m\033[Kt\033[m\033[K\033[01;31m\033[Ke\033[m\033[K\033[01;31m\033[Kr\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[Ki\033[m\033[K\033[01;31m\033[Kn\033[m\033[K\033[01;31m\033[Ka\033[m\033[K\033[01;31m\033[Kl\033[m\033[K\033[01;31m\033[K2\033[m\033[K
│   ├── \033[m\033[K\033[01;31m\033[Kk\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[Ko\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[K0\033[m\033[K\033[01;31m\033[K4\033[m\033[K\033[01;31m\033[K
│   │   ├── \033[m\033[K\033[01;31m\033[Ke\033[m\033[K\033[01;31m\033[Kr\033[m\033[K\033[01;31m\033[K2\033[m\033[K
│   │   ├── \033[m\033[K\033[01;31m\033[Ke\033[m\033[K\033[01;31m\033[Kx\033[m\033[K\033[01;31m\033[Kp\033[m\033[K\033[01;31m\033[Kr\033[m\033[K\033[01;31m\033[Ke\033[m\033[K\033[01;31m\033[Ks\033[m\033[K\033[01;31m\033[Ks\033[m\033[K\033[01;31m\033[K-\033[m\033[K\033[01;31m\033[Ks\033[m\033[K\033[01;31m\033[Kq\033[m\033[K\033[01;31m\033[Kl\033[m\033[K
│   │   ├── \033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[Ky\033[m\033[K\033[01;31m\033[Ke\033[m\033[K\033[01;31m\033[Kx\033[m\033[K\033[01;31m\033[Kp\033[m\033[K\033[01;31m\033[Kr\033[m\033[K\033[01;31m\033[Ke\033[m\033[K\033[01;31m\033[Ks\033[m\033[K\033[01;31m\033[Ks\033[m\033[K
│   │   └── \033[m\033[K\033[01;31m\033[Kt\033[m\033[K\033[01;31m\033[Kr\033[m\033[K\033[01;31m\033[Ka\033[m\033[K\033[01;31m\033[Kn\033[m\033[K\033[01;31m\033[Ks\033[m\033[K
│   ├── \033[m\033[K\033[01;31m\033[Kk\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[Ko\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[K0\033[m\033[K\033[01;31m\033[K5\033[m\033[K\033[01;31m\033[K
│   │   ├── \033[m\033[K\033[01;31m\033[Kc\033[m\033[K\033[01;31m\033[Kr\033[m\033[K\033[01;31m\033[Ku\033[m\033[K\033[01;31m\033[Kd\033[m\033[K
│   │   ├── \033[m\033[K\033[01;31m\033[Ke\033[m\033[K\033[01;31m\033[Ks\033[m\033[K\033[01;31m\033[Kh\033[m\033[K\033[01;31m\033[Ko\033[m\033[K\033[01;31m\033[Kp\033[m\033[K\033[01;31m\033[K1\033[m\033[K
│   │   └── \033[m\033[K\033[01;31m\033[Kp\033[m\033[K\033[01;31m\033[Kr\033[m\033[K\033[01;31m\033[Ko\033[m\033[K\033[01;31m\033[Kg\033[m\033[K
│   ├── \033[m\033[K\033[01;31m\033[Kk\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[Ko\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[K0\033[m\033[K\033[01;31m\033[K6\033[m\033[K\033[01;31m\033[K
│   │   ├── \033[m\033[K\033[01;31m\033[Ke\033[m\033[K\033[01;31m\033[Ks\033[m\033[K\033[01;31m\033[Kh\033[m\033[K\033[01;31m\033[Ko\033[m\033[K\033[01;31m\033[Kp\033[m\033[K\033[01;31m\033[K2\033[m\033[K
│   │   ├── \033[m\033[K\033[01;31m\033[Kf\033[m\033[K\033[01;31m\033[Ku\033[m\033[K\033[01;31m\033[Kn\033[m\033[K\033[01;31m\033[Kc\033[m\033[K
│   │   └── \033[m\033[K\033[01;31m\033[Ki\033[m\033[K\033[01;31m\033[Kn\033[m\033[K\033[01;31m\033[Kd\033[m\033[K\033[01;31m\033[Ke\033[m\033[K\033[01;31m\033[Kx\033[m\033[K
│   ├── \033[m\033[K\033[01;31m\033[Kk\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[Ko\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[K1\033[m\033[K\033[01;31m\033[K0\033[m\033[K\033[01;31m\033[K
│   │   ├── \033[m\033[K\033[01;31m\033[Ke\033[m\033[K\033[01;31m\033[Ks\033[m\033[K\033[01;31m\033[Kh\033[m\033[K\033[01;31m\033[Ko\033[m\033[K\033[01;31m\033[Kp\033[m\033[K\033[01;31m\033[K3\033[m\033[K
│   │   ├── \033[m\033[K\033[01;31m\033[Kp\033[m\033[K\033[01;31m\033[Kr\033[m\033[K\033[01;31m\033[Ke\033[m\033[K\033[01;31m\033[Kp\033[m\033[K
│   │   ├── \033[m\033[K\033[01;31m\033[Kt\033[m\033[K\033[01;31m\033[Kr\033[m\033[K\033[01;31m\033[Ky\033[m\033[K\033[01;31m\033[K1\033[m\033[K
│   │   ├── \033[m\033[K\033[01;31m\033[Kt\033[m\033[K\033[01;31m\033[Kr\033[m\033[K\033[01;31m\033[Ky\033[m\033[K\033[01;31m\033[K2\033[m\033[K
│   │   └── \033[m\033[K\033[01;31m\033[Kt\033[m\033[K\033[01;31m\033[Kr\033[m\033[K\033[01;31m\033[Ky\033[m\033[K\033[01;31m\033[K3\033[m\033[K
│   ├── \033[m\033[K\033[01;31m\033[Kr\033[m\033[K\033[01;31m\033[Ke\033[m\033[K\033[01;31m\033[Kd\033[m\033[K\033[01;31m\033[Ko\033[m\033[K\033[01;31m\033[Kv\033[m\033[K\033[01;31m\033[Ki\033[m\033[K\033[01;31m\033[Ks\033[m\033[K\033[01;31m\033[Ka\033[m\033[K
│   └── \033[m\033[K\033[01;31m\033[Ks\033[m\033[K\033[01;31m\033[Kk\033[m\033[K\033[01;31m\033[Ko\033[m\033[K\033[01;31m\033[Kl\033[m\033[K\033[01;31m\033[Ka\033[m\033[K\033[01;31m\033[Kn\033[m\033[K
├── LICENSE
├── Makefile
├── README.md

**Comment by neskoc** [comment]
Har nu testat design på nytt och det är likadant problem där:
design]$ tree .
.
├── \033[01;31m\033[Km\033[m\033[K\033[01;31m\033[Ke\033[m\033[K\033[01;31m\033[K
│   ├── \033[m\033[K\033[01;31m\033[Kk\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[Ko\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[K0\033[m\033[K\033[01;31m\033[K1\033[m\033[K
│   ├── \033[m\033[K\033[01;31m\033[Kk\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[Ko\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[K0\033[m\033[K\033[01;31m\033[K2\033[m\033[K
│   ├── \033[m\033[K\033[01;31m\033[Kk\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[Ko\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[K0\033[m\033[K\033[01;31m\033[K2\033[m\033[K\033[01;31m\033[K
│   │   └── \033[m\033[K\033[01;31m\033[Ks\033[m\033[K\033[01;31m\033[Ka\033[m\033[K\033[01;31m\033[Ks\033[m\033[K\033[01;31m\033[Ks\033[m\033[K
│   ├── \033[m\033[K\033[01;31m\033[Kk\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[Ko\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[K0\033[m\033[K\033[01;31m\033[K3\033[m\033[K
│   ├── \033[m\033[K\033[01;31m\033[Kk\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[Ko\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[K0\033[m\033[K\033[01;31m\033[K4\033[m\033[K
│   ├── \033[m\033[K\033[01;31m\033[Kk\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[Ko\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[K0\033[m\033[K\033[01;31m\033[K5\033[m\033[K
│   ├── \033[m\033[K\033[01;31m\033[Kk\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[Ko\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[K0\033[m\033[K\033[01;31m\033[K6\033[m\033[K
│   ├── \033[m\033[K\033[01;31m\033[Kk\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[Ko\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[K1\033[m\033[K\033[01;31m\033[K0\033[m\033[K
│   └── \033[m\033[K\033[01;31m\033[Kp\033[m\033[K\033[01;31m\033[Ko\033[m\033[K\033[01;31m\033[Kr\033[m\033[K\033[01;31m\033[Kt\033[m\033[K\033[01;31m\033[Kf\033[m\033[K\033[01;31m\033[Ko\033[m\033[K\033[01;31m\033[Kl\033[m\033[K\033[01;31m\033[Ki\033[m\033[K\033[01;31m\033[Ko\033[m\033[K

**Comment by mosbth** [comment]
Dubbelkolla att du är på en plats som är en lokal hårddisk och inte en nätverksdisk.

Visa utskriften från följande kommandon i databas-repot:

```
make clean-me
dbwebb init-me
file .dbwebb.map
df -k .
```

**Comment by mosbth** [comment]
Om vi inte kan klura ut något av kommandona ovan så vore det bra om du körde följande kommandon och sparade deras utskrift i varsin gist som du länkar till.

```
dbwebb check
dbwebb troubleshoot 
```

**Comment by neskoc** [comment]
De resultat jag redovisat i tråden kommer från en parallell repo på en icke-delad mapp dvs. utanför Dropbox

`make clean-me`

--->  # target: clean-me                - Remove me-directory.
rm -rf me

databas]$ dbwebb init-me
Creating and initiating the directory structure in 'me/' (will not overwrite existing files).
me/skolan
me/kmom01/klient
me/kmom02/js
me/kmom02/search
me/kmom02/terminal1
me/kmom03/cli
me/kmom03/terminal2
me/kmom03/er1
me/kmom04/er2
me/kmom04/trans
me/kmom04/myexpress
me/kmom04/express-sql
me/kmom05/prog
me/kmom05/crud
me/kmom05/eshop1
me/kmom06/func
me/kmom06/index
me/kmom06/eshop2
me/kmom10/eshop3
me/kmom10/try1
me/kmom10/try2
me/kmom10/try3
me/kmom10/prep
me/redovisa
DONE to init the directory 'me/'.

`file .dbwebb`

.dbwebb/                 .dbwebb-validate.config  .dbwebb.course           .dbwebb.map              .dbwebb.moss             .dbwebb.tests
(base) [nesko@NenadsMacBP databas]$ file .dbwebb.map
.dbwebb.map: ASCII text
(base) [nesko@NenadsMacBP databas]$ df -k .
Filesystem 1024-blocks      Used Available Capacity iused      ifree %iused  Mounted on
/dev/disk1   731240448 211237348 519747100    29% 3371772 4291595507    0%   /
(base) [nesko@NenadsMacBP databas]$ tree .
.
├── \033[01;31m\033[Km\033[m\033[K\033[01;31m\033[Ke\033[m\033[K\033[01;31m\033[K
│   ├── \033[m\033[K\033[01;31m\033[Kk\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[Ko\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[K0\033[m\033[K\033[01;31m\033[K1\033[m\033[K\033[01;31m\033[K
│   │   └── \033[m\033[K\033[01;31m\033[Kk\033[m\033[K\033[01;31m\033[Kl\033[m\033[K\033[01;31m\033[Ki\033[m\033[K\033[01;31m\033[Ke\033[m\033[K\033[01;31m\033[Kn\033[m\033[K\033[01;31m\033[Kt\033[m\033[K
│   ├── \033[m\033[K\033[01;31m\033[Kk\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[Ko\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[K0\033[m\033[K\033[01;31m\033[K2\033[m\033[K\033[01;31m\033[K
│   │   ├── \033[m\033[K\033[01;31m\033[Kj\033[m\033[K\033[01;31m\033[Ks\033[m\033[K
│   │   ├── \033[m\033[K\033[01;31m\033[Ks\033[m\033[K\033[01;31m\033[Ke\033[m\033[K\033[01;31m\033[Ka\033[m\033[K\033[01;31m\033[Kr\033[m\033[K\033[01;31m\033[Kc\033[m\033[K\033[01;31m\033[Kh\033[m\033[K
│   │   └── \033[m\033[K\033[01;31m\033[Kt\033[m\033[K\033[01;31m\033[Ke\033[m\033[K\033[01;31m\033[Kr\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[Ki\033[m\033[K\033[01;31m\033[Kn\033[m\033[K\033[01;31m\033[Ka\033[m\033[K\033[01;31m\033[Kl\033[m\033[K\033[01;31m\033[K1\033[m\033[K
│   ├── \033[m\033[K\033[01;31m\033[Kk\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[Ko\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[K0\033[m\033[K\033[01;31m\033[K3\033[m\033[K\033[01;31m\033[K
│   │   ├── \033[m\033[K\033[01;31m\033[Kc\033[m\033[K\033[01;31m\033[Kl\033[m\033[K\033[01;31m\033[Ki\033[m\033[K
│   │   ├── \033[m\033[K\033[01;31m\033[Ke\033[m\033[K\033[01;31m\033[Kr\033[m\033[K\033[01;31m\033[K1\033[m\033[K
│   │   └── \033[m\033[K\033[01;31m\033[Kt\033[m\033[K\033[01;31m\033[Ke\033[m\033[K\033[01;31m\033[Kr\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[Ki\033[m\033[K\033[01;31m\033[Kn\033[m\033[K\033[01;31m\033[Ka\033[m\033[K\033[01;31m\033[Kl\033[m\033[K\033[01;31m\033[K2\033[m\033[K
│   ├── \033[m\033[K\033[01;31m\033[Kk\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[Ko\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[K0\033[m\033[K\033[01;31m\033[K4\033[m\033[K\033[01;31m\033[K
│   │   ├── \033[m\033[K\033[01;31m\033[Ke\033[m\033[K\033[01;31m\033[Kr\033[m\033[K\033[01;31m\033[K2\033[m\033[K
│   │   ├── \033[m\033[K\033[01;31m\033[Ke\033[m\033[K\033[01;31m\033[Kx\033[m\033[K\033[01;31m\033[Kp\033[m\033[K\033[01;31m\033[Kr\033[m\033[K\033[01;31m\033[Ke\033[m\033[K\033[01;31m\033[Ks\033[m\033[K\033[01;31m\033[Ks\033[m\033[K\033[01;31m\033[K-\033[m\033[K\033[01;31m\033[Ks\033[m\033[K\033[01;31m\033[Kq\033[m\033[K\033[01;31m\033[Kl\033[m\033[K
│   │   ├── \033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[Ky\033[m\033[K\033[01;31m\033[Ke\033[m\033[K\033[01;31m\033[Kx\033[m\033[K\033[01;31m\033[Kp\033[m\033[K\033[01;31m\033[Kr\033[m\033[K\033[01;31m\033[Ke\033[m\033[K\033[01;31m\033[Ks\033[m\033[K\033[01;31m\033[Ks\033[m\033[K
│   │   └── \033[m\033[K\033[01;31m\033[Kt\033[m\033[K\033[01;31m\033[Kr\033[m\033[K\033[01;31m\033[Ka\033[m\033[K\033[01;31m\033[Kn\033[m\033[K\033[01;31m\033[Ks\033[m\033[K
│   ├── \033[m\033[K\033[01;31m\033[Kk\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[Ko\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[K0\033[m\033[K\033[01;31m\033[K5\033[m\033[K\033[01;31m\033[K
│   │   ├── \033[m\033[K\033[01;31m\033[Kc\033[m\033[K\033[01;31m\033[Kr\033[m\033[K\033[01;31m\033[Ku\033[m\033[K\033[01;31m\033[Kd\033[m\033[K
│   │   ├── \033[m\033[K\033[01;31m\033[Ke\033[m\033[K\033[01;31m\033[Ks\033[m\033[K\033[01;31m\033[Kh\033[m\033[K\033[01;31m\033[Ko\033[m\033[K\033[01;31m\033[Kp\033[m\033[K\033[01;31m\033[K1\033[m\033[K
│   │   └── \033[m\033[K\033[01;31m\033[Kp\033[m\033[K\033[01;31m\033[Kr\033[m\033[K\033[01;31m\033[Ko\033[m\033[K\033[01;31m\033[Kg\033[m\033[K
│   ├── \033[m\033[K\033[01;31m\033[Kk\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[Ko\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[K0\033[m\033[K\033[01;31m\033[K6\033[m\033[K\033[01;31m\033[K
│   │   ├── \033[m\033[K\033[01;31m\033[Ke\033[m\033[K\033[01;31m\033[Ks\033[m\033[K\033[01;31m\033[Kh\033[m\033[K\033[01;31m\033[Ko\033[m\033[K\033[01;31m\033[Kp\033[m\033[K\033[01;31m\033[K2\033[m\033[K
│   │   ├── \033[m\033[K\033[01;31m\033[Kf\033[m\033[K\033[01;31m\033[Ku\033[m\033[K\033[01;31m\033[Kn\033[m\033[K\033[01;31m\033[Kc\033[m\033[K
│   │   └── \033[m\033[K\033[01;31m\033[Ki\033[m\033[K\033[01;31m\033[Kn\033[m\033[K\033[01;31m\033[Kd\033[m\033[K\033[01;31m\033[Ke\033[m\033[K\033[01;31m\033[Kx\033[m\033[K
│   ├── \033[m\033[K\033[01;31m\033[Kk\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[Ko\033[m\033[K\033[01;31m\033[Km\033[m\033[K\033[01;31m\033[K1\033[m\033[K\033[01;31m\033[K0\033[m\033[K\033[01;31m\033[K
│   │   ├── \033[m\033[K\033[01;31m\033[Ke\033[m\033[K\033[01;31m\033[Ks\033[m\033[K\033[01;31m\033[Kh\033[m\033[K\033[01;31m\033[Ko\033[m\033[K\033[01;31m\033[Kp\033[m\033[K\033[01;31m\033[K3\033[m\033[K
│   │   ├── \033[m\033[K\033[01;31m\033[Kp\033[m\033[K\033[01;31m\033[Kr\033[m\033[K\033[01;31m\033[Ke\033[m\033[K\033[01;31m\033[Kp\033[m\033[K
│   │   ├── \033[m\033[K\033[01;31m\033[Kt\033[m\033[K\033[01;31m\033[Kr\033[m\033[K\033[01;31m\033[Ky\033[m\033[K\033[01;31m\033[K1\033[m\033[K
│   │   ├── \033[m\033[K\033[01;31m\033[Kt\033[m\033[K\033[01;31m\033[Kr\033[m\033[K\033[01;31m\033[Ky\033[m\033[K\033[01;31m\033[K2\033[m\033[K
│   │   └── \033[m\033[K\033[01;31m\033[Kt\033[m\033[K\033[01;31m\033[Kr\033[m\033[K\033[01;31m\033[Ky\033[m\033[K\033[01;31m\033[K3\033[m\033[K
│   ├── \033[m\033[K\033[01;31m\033[Kr\033[m\033[K\033[01;31m\033[Ke\033[m\033[K\033[01;31m\033[Kd\033[m\033[K\033[01;31m\033[Ko\033[m\033[K\033[01;31m\033[Kv\033[m\033[K\033[01;31m\033[Ki\033[m\033[K\033[01;31m\033[Ks\033[m\033[K\033[01;31m\033[Ka\033[m\033[K
│   └── \033[m\033[K\033[01;31m\033[Ks\033[m\033[K\033[01;31m\033[Kk\033[m\033[K\033[01;31m\033[Ko\033[m\033[K\033[01;31m\033[Kl\033[m\033[K\033[01;31m\033[Ka\033[m\033[K\033[01;31m\033[Kn\033[m\033[K
├── LICENSE
├── Makefile

**Comment by neskoc** [comment]
https://gist.github.com/neskoc/bf33ab34d9f5b175134e15154f72ad58
https://gist.github.com/neskoc/cd69aa64e15cde8131eceb5eac560b8a

Jag har löst problemet genom att köra init på linux och synka med Dropbox så jag är nöjd med det.
Har fullt upp för tillfället för att lägga mer tid på felsökning.
Mitt inlägg på discord var för kännedom i fall någon mer stöter på likadant problem.
Så för min del behöver du/ni inte lägga mer tid på det.

**Comment by mosbth** [comment]
Då låter vi det vara.
Det syns inget speciellt i dina loggar och jag känner inte igen felet från tidigare.
Vi hade behövt se mer på din miljö och vad det är som skiljer den från andra när kommandot `dbwebb init-me` körs.

Den koden som körs bakom kulisserna ser ut ungefär så här:

```
    local mapFile="$DBW_COURSE_DIR/.dbwebb.map"
    if [ -f "$mapFile" ]; then
        while IFS= read -r path
        do
            echo "$path"
            install -d "$DBW_COURSE_DIR/$path"
        done < <(grep "^[^#]" "$mapFile")
    fi
```

Vi hade fått anpassa detta skriptet till din miljö och testköra det för att se om något av kommandona ger oväntat resultat på din miljö. 

Möjligen kan det ha med `grep` kommandot att göra. Utskriften från det borde se ut så här.

```
$ grep "^[^#]" .dbwebb.map 
me/skolan                  
me/kmom01/klient           
me/kmom02/js               
me/kmom02/search           
me/kmom02/terminal1        
me/kmom03/cli              
me/kmom03/terminal2        
me/kmom03/er1              
me/kmom04/er2              
me/kmom04/trans            
me/kmom04/myexpress        
me/kmom04/express-sql      
me/kmom05/prog             
me/kmom05/crud             
me/kmom05/eshop1           
me/kmom06/func             
me/kmom06/index            
me/kmom06/eshop2           
me/kmom10/eshop3           
me/kmom10/try1             
me/kmom10/try2             
me/kmom10/try3             
me/kmom10/prep             
me/redovisa                
```

Men, låt det vara så ser vi om nån annan tar upp samma spår.
