### ISSUE TITLE
MacOs Big Sur och Workbench

### ISSUE THREAD

**Issue by lewenhagen** [dbwebb-se/databas#15]
Om man kör Big Sur kan det hända att workbench krashar vid start. En lösning är att installera via 

`brew install --cask mysqlworkbench` 

istället för .dmg filen.

**Comment by lewenhagen** [comment]
Det kan hända att git slutar fungera efter uppdatering. En lösning är att köra:

`xcode-select --install`

**Comment by MollyK-A** [comment]
Jag försökte detta, men Workbench kraschar fortfarande vid start. Jag körde xcode-select --install men fick "xcode-select: error: command line tools are already installed, use "Software Update" to install updates".

<img width="481" alt="Skärmavbild 2021-01-20 kl  11 37 52" src="https://user-images.githubusercontent.com/73881134/105163224-f05c0200-5b13-11eb-87ab-17fbeee749ee.png">

**Comment by MollyK-A** [comment]
Jag fick workbench att fungera på Big Sur genom att ladda ner en tidigare version (8.0.21 istället för 8.0.22).

**Comment by mosbth** [comment]
Jag installerade senaste versionen av Workbench 8.0.27 via DMG filen och det fungerar. Jag har dock ännu inte kört "hårt" så jag har inte full koll på om det fungerar smärtfritt.
