### ISSUE TITLE
Lösenord syns i klartext i Cygwin

### ISSUE THREAD

**Issue by lewenhagen** [dbwebb-se/databas#18]
Relevant del i guiden: https://dbwebb.se/guide/kom-igang-med-sql-i-mysql/aterstall-databasen-del-1

Vissa får bekymmer när man exekverar scripet "reset_part1.bash". 
Delen som krånglar: `mysql -uroot -p < setup.sql > /dev/null`

När lösenordet efterfrågas syns inputen i klartext och scriptet går sönder.

Det fungerar med: `mysql -uroot -ppass < setup.sql > /dev/null`.

**Comment by mosbth** [comment]
Någon info om exakt felutskrift eller på vilka mijlöer det händer, typ cygwin eller liknande?

**Comment by lewenhagen** [comment]
Vad jag sett kommer det ingen felutskrift, verkar som scriptet hamnar i nåt vänteläge.
Som titeln anger så är det Cygwin. Om mysql är installerat via apt-cyg eller ej är oklart.

**Comment by mosbth** [comment]
> Om mysql är installerat via apt-cyg eller ej är oklart.

Om någon har möjlighet att testa så kör man kommandot `which mysql` för att ta reda på vilken version man kör.

**Comment by Westy90** [comment]
Hej,

Det är cygwin som jag kör i windows 10.

när jag slår kommandot which mysql så får jag en sökväg som innehåller: 
/cygdrive/c/program files/mysql/MySQL Server 8.0/bin/mysql

**Comment by mosbth** [comment]
Då låter det som du missat installera mysql in i Cygwin. När man kör Windowsklienten i Cygwin så får man vissa udda beteenden.

Det stod en not om det här i installationsdokumentet.
https://dbwebb.se/kunskap/installera-mysql-server-och-mysql-workbench-pa-windows-10#win10cygwin

`apt install mysql`

**Comment by Westy90** [comment]
Hej! Det verkar som problemet har lösts nu efter att jag följde mikaels hänvisning. Tack!
