### ISSUE TITLE
Kursutveckling vt18 lp4

### ISSUE THREAD

**Issue by mosbth** [dbwebb-se/databas#2]
Tankar och idéer i samband med kurstillfället i vt18 lp4.

## Generellt

* Ett PHP-spår (Python) som alternativ till JavaScript/Node?
* Inkludera exempel på transpose & pivot table.

## Labbmiljön

* Skriv om artikeln "[Kom igång med databasen MySQL och dess klienter](https://dbwebb.se/kunskap/kom-igang-med-databasen-mysql-och-dess-klienter)" och dela upp den i delar, del om MySQL, generell del om klienter, egen artikel om hur klienterna fungerar i XAMPP.

## Guiden

* Jobba genom guiden och streamlina den, eventuellt fördjupa delarna och förfina när reset behövs.
* DD automatiskt genererat från databasen.
* Hur man godkänner ett kurstillfälle kan uppfattas på olika sätt, kanske är det inte jätteanvändarvänligt.
* Använd relativa sökvägar i LOAD DATA LOCAL INFILE https://dbwebb.se/guide/kom-igang-med-sql-i-mysql/importera-fran-excel-till-tabell
* Sista stycket, länka till trans, udf, etc i respektive artikel, så det finns en länkt till artikel om howto.
* Create user funkar annorlunda i MySQL 8.

## Example

* npm install hamnar i kursrepots package.json vilket krockar vid dbwebb update, försök hantera det bättre.

## Läsanvisningar

* HItta korta artiklar om databaser, modellering och hur saker fungerar i världen med databaser. En/två per kmom som bredvisläsning och ta upp på fläs.
* Flytta foruminlägget till guiden? Vad välja som primärnyckel till en databastabell
* Orientering om databaser och olika typer av databaser (vilket kmom?, flera?)

## npm install och package.json

* Se till att allt installeras i respektive katalog och inte i kursrepots package.json.

## Exam

* Gör fyra uppgifter om 10p och inte en stor 3:a. Öka svårighetsgraden?
* Om uppgift om CRUD, var tydlig att alla delar önskas.
* Skriv att webbklienten skall börja på /.
* Tips om att flytta allt gammalt till old eller liknande.

**Comment by mosbth** [comment]
### Projektet

* Räntor, överför alla beräknade räntor från räntekontot till användarens konto.
* Gör så att swish-grejen inte är så lik en överföring, den ska bara swisha till annat konto i "annan bank" så att pengarna försvinner från banken.

**Comment by lewenhagen** [comment]
#### Städa i guiden
* kmom01
* kmom02
* kmom03
    * läsa från csv (visa relativa sökvägar) [foruminlägg](https://dbwebb.se/forum/viewtopic.php?f=73&t=7406#p59990)
    * skriva till csv Forum: [access denied](https://dbwebb.se/forum/viewtopic.php?f=73&t=7404#p59988), [secure-file-priv](https://dbwebb.se/forum/viewtopic.php?f=73&t=7405#p59989), [enklare varianten](https://dbwebb.se/forum/viewtopic.php?f=73&t=7407#p59991)
* kmom04
* kmom05
* kmom06

**Comment by mosbth** [comment]
Blandad studentfeedback.

* Enda kritiken jag har är den ovan nämnda obalans gällande den poäng som ges av projektarbetet i förhållande till examinationen.

**Comment by mosbth** [comment]
Kursutvärderingen finns i sin helhet inkl fritextkommentarer, via:
http://bfm.bth.se/public/rapport/18874d11-e1c8-426b-a287-74ef5b607ab2  

Kursutvärderingen är gjord på kursen "Objektorienterade webbteknologier", men alla svaren rör databas-kursen (interna problem med BTHs kursutvärderingssystem som inte gick att åtgärda inför utskicket).

Svarsfrekvensen var 13/(35,1,22). Snittet blev 3.56.

Jag har sammanställt mina kommentarer, inklusive de kommentarer jag får av studenterna i kmom10, i ett dokument.
https://docs.google.com/document/d/1b7-1V0q5-0Znm5jDIZCkrQezx02btmKMcQ1KttLgfqY/edit?usp=sharing
