### ISSUE TITLE
Streamline kmom01

### ISSUE THREAD

**Issue by AndreasArne** [dbwebb-se/databas#3]
Mina onödigt petiga tankar för streamlining
## Labbmiljö
- Ta bort "kom igån" delen från labbmiljö: https://dbwebb.se/kurser/databas-v1/labbmiljo/mysql#kom
    - Varför har vi börjat med övningar i labbmiljön?
### Installera MYSQl/workbench
- Skriv om introduktion så du inte utgår från att de redan har installerat mysql-workbench. Här fastnar petare, förstår inte varför de inte hittar workbench. https://dbwebb.se/kunskap/installera-mysql-server-och-mysql-workbench#intro
- Vilken länk ska användas "Nedladdning" eller "Windows 10"? https://dbwebb.se/kunskap/installera-mysql-server-och-mysql-workbench#download
    - Flytta första länken till Mac os delen där den faktist används
- Windows 10: Vilken installer ska användas: https://dev.mysql.com/downloads/installer/#current-tab. De har samma namn, vad är skillnaden.
- "Eventuella verktyg som behövs", vad är det, när kan det behövas? Senare i kursen eller bara för att det ska fungera på datorn? https://dbwebb.se/kunskap/installera-mysql-server-och-mysql-workbench#win10
- Ska de skapa en användare? Vilken roll bör den ha?
- Ska de enabla "Mysql as document store"?
- Många steg som sker under installationen som inte nämna i instruktionerna.
- Kommandot för att köra mysql i terminalen funkar inte. Behöver ```"``` runt pathen. ```"C:\Program Files\MySQL\MySQL Server 5.7\bin\mysql.exe" -uroot -p```. https://dbwebb.se/kunskap/installera-mysql-server-och-mysql-workbench#winterminal
### XAMPPinstallation
- Hur ska de göra om de redan har xampp installerat? installera om? https://dbwebb.se/labbmiljo/mysql#xampp
## Kom igång med Mysql och klienter
- Förväntaas att de ska installera i XAMPP? https://dbwebb.se/kunskap/kom-igang-med-databasen-mysql-och-dess-klienter#pre. Eller varför står det bara om den installationen under "Förutsättningar"?
## Kom igång med sql i myslq
- Vad är första delene i guiden? https://dbwebb.se/kurser/databas-v1/kmom01#uppgifter
- Vad gör/betyder koden för att skapa en tabell? https://dbwebb.se/guide/kom-igang-med-sql-i-mysql/skapa-tabell
## Generellt för sql guiden
- förklarar inte innebörden av koden eller databaser. Mer kör dett kommandot så händer detta.
- Bra om man redan vet vad en databas är/hur den fungerar, men om man inte redan har den kunskapen eller letar upp den på annat håll kan det nog vara svårt eller bara copy-paste utan lära sig.
    - Var tydlig med var de ska få den informationen, föreläsning/kursbok/googla?

**Comment by mosbth** [comment]
Fixade några.

Tog bort övningen från installationsdelen och finns nu endast i Övning.
lade även till "varningstexten" om att XAMPP finns i artikeln och säger de kan hopp de bitarna.

Skrev om hur "första delen av guiden" länkas och refereras till i uppgiftstexten.

Guiden om MySQL skall skrivas bort så att spåren till XAMPP försvinner. Det är noterat i #2.

Dock finns inget som egentligen hindrar att de väljer att jobba med en installation av MySQL i XAMPP. Men i instruktionerna skall det inte synas.
