### ISSUE TITLE
AI felaktig

### ISSUE THREAD

**Issue by fahlstrm** [dbwebb-se/databas#30]
Läser in data i tabell via .csv, totalt 6 rader vilka visas korrekt i klienten/terminalen.
När jag sedan lägger till ett värde i klienten (via en SP) ges productcode(index) 8. Den hoppar alltså över 7an.

**Comment by mosbth** [comment]
Man kan inte riktigt lita på att AI är konsekvent, det är ett autoincrementerande värde man vi kan inte vara helt säkra på att de värdena kommer i en sekvens. man måste alltid kolla vad det senaste värdet är, om man vill använda det.
