### ISSUE TITLE
Flytta allt från CLI till Express

### ISSUE THREAD

**Issue by pereriksson** [dbwebb-se/databas#32]
Hej!

Ville bara föreslå att kommande versioner av databaskursen plockar bort CLI-klienten till förmån för ett helt webbaserat gränssnitt i Express.

CLI-verktyg känns lite gammalmodigt. Vi är ju ändå ett högskoleprogram inom webbprogrammering. Dessutom så flyttar alla moderna administrativa gränssnitt inom t ex e-handel, WMS, ERP ut på nätet och blir webbaserade (se exempel). Det skulle därför vara mer realistiskt att även administrativa funktioner fanns i det webbaserade gränssnittet (pick, ship, invadd, invdel etc).

Per

Exempel från Microsoft Business Central (ERP)
![Microsoft Business Central (ERP)](https://user-images.githubusercontent.com/2284872/112330421-51d95200-8cb8-11eb-94fa-5ac7815f68e1.png)

Exempel från Ongoing (WMS)
<img width="483" alt="Ongoing (WMS)" src="https://user-images.githubusercontent.com/2284872/112330428-530a7f00-8cb8-11eb-850d-508cb6aee3f5.png">

**Comment by mosbth** [comment]
Jag funderar lite fram och tillbaka, för tillfället är CLI kvar, får se hur det blir i framtiden.
