### ISSUE TITLE
Välj MySQL eller MariaDB + version

### ISSUE THREAD

**Issue by pereriksson** [dbwebb-se/databas#35]
Hej!

Min feedback inför kommande versioner av kursen är att välja MySQL eller MariaDB i denna kurs. Fokuset bör vara på lärandet och inte att felsöka olika skillnader dem emellan eller att välja rätt variant av kommandot i instruktionerna. Av del anledningen vore bättre att se MariaDB och MySQL som olika databasmotorer.

Samma gäller olika versioner, det är bättre att bestämma vilken version man ska köra. En idé är kanske att använda Docker för att göra detta enklare på olika plattformar?

Exempel på saker som gjort kursen svårare:
"Om du får problem att koppla dig med godtycklig klient mot databasen MySQL 8.0.4 eller högre så kan det bero på implementationsdetaljer som rör hur lösenordet krypteras"
"Det finns en forumtråd, “Kompabilitet mellan MySQL och MariaDB, CREATE USER”, som förklarar detta i mer detalj."
"Detta är en lösning på problemet som inträffar när äldre klienter kopplar sig mot nyare databaser (MySQL från och med version 8.0.4). "

Per

**Comment by mosbth** [comment]
Håller på och funderar på hur jag vill göra. Det vore enklare om vi bara hade en databas så troligen försöker jag komma dit. 

Att "förenkla" är ett ledord när jag försöker förbättra kursen.
