### ISSUE TITLE
Ha en föreläsning om NoSQL och grafdatabaser

### ISSUE THREAD

**Issue by pereriksson** [dbwebb-se/databas#36]
En föreläsning om detta hade varit bra. Det bygger kompetens inför framtiden och det vore synd om bara jsramverk nämner detta.

Förslag på scope:
* Hur dessa databastyper fungerar
* I vilka projekt de passar
* Styrkor och svagheter mot relationella databaser

**Comment by emilfolino** [comment]
Kan bara tillägga att fokus på NoSQL kommer öka i jsramverk inför hösten 21

**Comment by mosbth** [comment]
En bra idé, om jag får in det i kursen. Försöker för tillfället plocka bort saker från kursen...
